[package]
name = "nfl_predictor_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.27.2"
polars-core = {version = "0.27.2", features=["ndarray", "lazy"]}
smartcore = "0.3.0"